import { useMemo, useState } from 'react'
import { ArrowUpRight, CalendarDays, CheckCircle2, ChevronDown, ClipboardList, Eye, FilePenLine, GraduationCap, Plus, Search, X } from 'lucide-react'
import { emptyScholarship, scholarshipSeed } from './data'

const states = ['All states', 'Bihar', 'Haryana', 'Jharkhand']
const statuses = ['Published', 'Draft', 'Expired']
const indianStates = ['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal', 'Andaman and Nicobar Islands', 'Chandigarh', 'Dadra and Nagar Haveli and Daman and Diu', 'Delhi', 'Jammu and Kashmir', 'Ladakh', 'Lakshadweep', 'Puducherry']

const formatDate = (date) => date ? new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(`${date}T00:00:00`)) : 'Not stated'

function StatusBadge({ status }) { return <span className={`badge badge-${status.toLowerCase()}`}>{status}</span> }

function StatePicker({ value, onChange }) {
  const [open, setOpen] = useState(false)
  const matches = indianStates.filter((state) => state.toLowerCase().includes(value.toLowerCase())).slice(0, 7)
  return <div className="state-picker"><input value={value} onFocus={() => setOpen(true)} onChange={(e) => { onChange(e.target.value); setOpen(true) }} placeholder="Start typing a state" aria-label="State" aria-expanded={open} aria-autocomplete="list" /><ChevronDown size={17} className="picker-chevron" /><button type="button" className="picker-toggle" onMouseDown={(e) => e.preventDefault()} onClick={() => setOpen((current) => !current)} aria-label="Show state suggestions" />{open && <div className="state-options" role="listbox">{matches.length ? matches.map((state) => <button key={state} type="button" role="option" onMouseDown={(e) => e.preventDefault()} onClick={() => { onChange(state); setOpen(false) }}>{state}</button>) : <p>No matching state found</p>}</div>}</div>
}

function ScholarshipForm({ scholarship, onClose, onSave }) {
  const [form, setForm] = useState(scholarship ?? emptyScholarship)
  const [errors, setErrors] = useState({})
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }))
  const submit = (event) => {
    event.preventDefault()
    const nextErrors = {}
    ;['name', 'state', 'provider', 'classes', 'eligibility', 'benefit', 'link'].forEach((field) => { if (!form[field]?.trim()) nextErrors[field] = 'This field is required.' })
    if (form.link && !/^https?:\/\//.test(form.link)) nextErrors.link = 'Enter a valid URL starting with http:// or https://.'
    if (Object.keys(nextErrors).length) return setErrors(nextErrors)
    onSave({ ...form, id: scholarship?.id ?? Date.now() })
  }
  const field = (label, key, type = 'text', props = {}) => <label className="field"><span>{label} <b>*</b></span><input type={type} value={form[key]} onChange={(e) => update(key, e.target.value)} aria-invalid={Boolean(errors[key])} {...props} />{errors[key] && <small>{errors[key]}</small>}</label>
  return <div className="overlay" role="presentation"><section className="modal form-modal" role="dialog" aria-modal="true" aria-label={scholarship ? 'Edit scholarship' : 'Add scholarship'}><header className="modal-header"><div><p className="eyebrow">Scholarship record</p><h2>{scholarship ? 'Edit scholarship' : 'Add scholarship'}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close form"><X size={20} /></button></header><form onSubmit={submit}><div className="form-grid">{field('Scholarship name', 'name')}<label className="field"><span>State <b>*</b></span><StatePicker value={form.state} onChange={(value) => update('state', value)} /></label>{field('Provider name', 'provider')}{field('Applicable class', 'classes')}<label className="field full"><span>Eligibility criteria <b>*</b></span><textarea value={form.eligibility} onChange={(e) => update('eligibility', e.target.value)} rows="3" />{errors.eligibility && <small>{errors.eligibility}</small>}</label>{field('Scholarship amount or benefit', 'benefit')} {field('Application deadline', 'deadline', 'date')} {field('Official application link', 'link', 'url', { placeholder: 'https://example.gov.in' })}<label className="field"><span>Status</span><select value={form.status} onChange={(e) => update('status', e.target.value)}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></label></div><footer className="modal-footer"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" type="submit">{scholarship ? 'Save changes' : 'Add scholarship'}</button></footer></form></section></div>
}

function Preview({ scholarship, onClose }) { return <div className="overlay" role="presentation"><section className="modal preview-modal" role="dialog" aria-modal="true" aria-label="Student scholarship preview"><header className="modal-header"><div><p className="eyebrow">Student view</p><h2>Scholarship preview</h2></div><button className="icon-button" onClick={onClose} aria-label="Close preview"><X size={20} /></button></header><article className="student-card"><div className="student-card-head"><div className="student-icon"><GraduationCap size={25} /></div><StatusBadge status={scholarship.status} /></div><p className="state-label">{scholarship.state}</p><h3>{scholarship.name}</h3><p className="provider">By {scholarship.provider}</p><div className="student-meta"><span><GraduationCap size={16} /> {scholarship.classes}</span><span><CalendarDays size={16} /> Deadline: {formatDate(scholarship.deadline)}</span></div><div className="detail-block"><strong>Eligibility</strong><p>{scholarship.eligibility}</p></div><div className="benefit"><span>Benefit</span><strong>{scholarship.benefit}</strong></div><a href={scholarship.link} target="_blank" rel="noreferrer" className="button primary apply-link">Visit application site <ArrowUpRight size={17} /></a></article></section></div> }

function ScholarshipCard({ item, onPreview, onStatusChange }) {
  return <article className="scholarship-card"><div className="card-top"><span className="card-icon"><GraduationCap size={21} /></span><div className="listing-meta"><span className="listing-type">Scholarship</span><small>✓ Verified listing</small></div></div><h3>{item.name}</h3><p className="provider">By {item.provider} · {item.state}</p><div className="award-panel"><span>✦ Scholarship award</span><strong>{item.benefit}</strong></div><div className="eligibility"><GraduationCap size={17} /><div><span>Who can apply</span><p>{item.eligibility}</p></div></div><div className="card-footer"><div className="deadline"><CalendarDays size={16} /><span><b>{item.deadline ? 'Deadline' : 'Date not stated'}</b><small>{formatDate(item.deadline)}</small></span></div><select className={`status-control ${item.status.toLowerCase()}`} value={item.status} onChange={(e) => onStatusChange(item.id, e.target.value)} aria-label={`Change ${item.name} status`}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></div><div className="card-actions"><button className="card-action preview-action" onClick={() => onPreview(item)} aria-label={`Preview ${item.name}`}><Eye size={16} /> Preview details</button></div></article>
}

export default function App() {
  const [scholarships, setScholarships] = useState(scholarshipSeed)
  const [stateFilter, setStateFilter] = useState('All states')
  const [query, setQuery] = useState('')
  const [formItem, setFormItem] = useState(undefined)
  const [previewItem, setPreviewItem] = useState(null)
  const [notice, setNotice] = useState('')
  const filtered = useMemo(() => scholarships.filter((item) => (stateFilter === 'All states' || item.state === stateFilter) && item.name.toLowerCase().includes(query.toLowerCase())), [scholarships, stateFilter, query])
  const counts = statuses.reduce((total, status) => ({ ...total, [status]: scholarships.filter((item) => item.status === status).length }), { Published: 0, Draft: 0, Expired: 0 })
  const save = (item) => { setScholarships((current) => current.some((entry) => entry.id === item.id) ? current.map((entry) => entry.id === item.id ? item : entry) : [item, ...current]); setFormItem(undefined); setNotice(`Scholarship ${item.id > 9 ? 'added' : 'updated'} successfully.`); setTimeout(() => setNotice(''), 3000) }
  const changeStatus = (id, status) => { setScholarships((current) => current.map((item) => item.id === id ? { ...item, status } : item)); setNotice('Status updated successfully.'); setTimeout(() => setNotice(''), 3000) }
  return <main><nav className="topbar"><a className="brand" href="#top"><span className="brand-mark">K</span><span>K12 Hunar <em>CRM</em></span></a><div className="employee"><span className="avatar">AK</span><span><b>Employee</b><small>Scholarship team</small></span></div></nav><div className="page" id="top"><section className="hero"><div><p className="eyebrow">Scholarship management</p><h1>Scholarships</h1><p className="subcopy">Create, publish, and manage opportunities for students.</p></div><button className="button primary add-button" onClick={() => setFormItem(null)}><Plus size={18} /> Add scholarship</button></section><section className="stat-grid" aria-label="Scholarship overview"><div className="stat-card total"><span className="stat-icon"><ClipboardList size={21} /></span><div><span>Total scholarships</span><strong>{scholarships.length}</strong></div></div><div className="stat-card published"><span className="stat-icon"><CheckCircle2 size={21} /></span><div><span>Published</span><strong>{counts.Published}</strong></div></div><div className="stat-card draft"><span className="stat-icon"><FilePenLine size={21} /></span><div><span>Draft</span><strong>{counts.Draft}</strong></div></div><div className="stat-card expired"><span className="stat-icon"><CalendarDays size={21} /></span><div><span>Expired</span><strong>{counts.Expired}</strong></div></div></section><section className="records"><header className="records-head"><div><h2>Scholarship records</h2><p>{filtered.length} of {scholarships.length} scholarships shown</p></div><div className="tools"><label className="search"><Search size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search scholarships" aria-label="Search scholarships" /></label><label className="state-select"><span>State</span><select value={stateFilter} onChange={(e) => setStateFilter(e.target.value)}>{states.map((state) => <option key={state}>{state}</option>)}</select></label></div></header><div className="card-grid">{filtered.map((item) => <ScholarshipCard key={item.id} item={item} onPreview={setPreviewItem} onStatusChange={changeStatus} />)}{!filtered.length && <div className="empty"><Search size={26} /><h3>No scholarships found</h3><p>Try another state or search term.</p></div>}</div></section></div>{notice && <div className="notice" role="status"><CheckCircle2 size={18} />{notice}</div>}{formItem !== undefined && <ScholarshipForm scholarship={formItem} onClose={() => setFormItem(undefined)} onSave={save} />}{previewItem && <Preview scholarship={previewItem} onClose={() => setPreviewItem(null)} />}</main>
}
