export const scholarshipSeed = [
  { id: 1, name: 'Post-Matric Scholarship BC EBC', state: 'Bihar', provider: 'Government of Bihar', classes: 'Class 11-12', eligibility: 'Students belonging to BC and EBC categories.', benefit: 'Tuition support', deadline: '2026-09-30', link: 'https://pmsonline.bih.nic.in/', status: 'Published' },
  { id: 2, name: 'Post-Matric Scholarship SC ST', state: 'Bihar', provider: 'Government of Bihar', classes: 'Class 11-12', eligibility: 'Students belonging to SC and ST categories.', benefit: 'Tuition support', deadline: '2026-09-30', link: 'https://pmsonline.bih.nic.in/', status: 'Draft' },
  { id: 3, name: 'Mukhyamantri Balak Balika Protsahan Yojana', state: 'Bihar', provider: 'Government of Bihar', classes: 'Class 9-10', eligibility: 'Eligible Bihar board students.', benefit: 'Merit-based incentive', deadline: '', link: 'https://education.bih.nic.in/', status: 'Expired' },
  { id: 4, name: 'Pre-Matric Scholarship for SC Students', state: 'Haryana', provider: 'Government of Haryana', classes: 'Class 9-10', eligibility: 'SC students studying in Haryana.', benefit: 'Annual scholarship', deadline: '2026-12-31', link: 'https://harchhatravratti.highereduhry.ac.in/', status: 'Published' },
  { id: 5, name: 'Pre-Matric Scholarship for BC Students', state: 'Haryana', provider: 'Government of Haryana', classes: 'Class 9-10', eligibility: 'BC students studying in Haryana.', benefit: 'Annual scholarship', deadline: '2026-12-31', link: 'https://harchhatravratti.highereduhry.ac.in/', status: 'Draft' },
  { id: 6, name: 'Post-Matric Scholarship for SC Students', state: 'Haryana', provider: 'Government of Haryana', classes: 'Class 11-12', eligibility: 'SC students enrolled in post-matric studies.', benefit: 'Tuition support', deadline: '2026-12-31', link: 'https://harchhatravratti.highereduhry.ac.in/', status: 'Expired' },
  { id: 7, name: 'Pre-Matric Scholarship for SC Students', state: 'Jharkhand', provider: 'Government of Jharkhand', classes: 'Class 1-10', eligibility: 'SC students studying in Jharkhand.', benefit: 'Annual scholarship', deadline: '2026-11-20', link: 'https://ekalyan.cgg.gov.in/', status: 'Published' },
  { id: 8, name: 'Pre-Matric Scholarship for ST Students', state: 'Jharkhand', provider: 'Government of Jharkhand', classes: 'Class 1-10', eligibility: 'ST students studying in Jharkhand.', benefit: 'Annual scholarship', deadline: '2026-11-20', link: 'https://ekalyan.cgg.gov.in/', status: 'Draft' },
  { id: 9, name: 'Pre-Matric Scholarship for BC OBC Students', state: 'Jharkhand', provider: 'Government of Jharkhand', classes: 'Class 1-10', eligibility: 'BC and OBC students studying in Jharkhand.', benefit: 'Annual scholarship', deadline: '2026-11-20', link: 'https://ekalyan.cgg.gov.in/', status: 'Expired' },
]

export const emptyScholarship = { name: '', state: '', provider: '', classes: '', eligibility: '', benefit: '', deadline: '', link: '', status: 'Draft' }
